export default class Localization {
    static HOME = {

        RELEASE_NOTES: "Release notes",
        RELEASES: "Releases",
        PROJECT_NAME: "My project",
        NO_VERSION_INSTALLED: "No editor installation found, please download one.",
        VERSION_WARNING: "Changing versions may break some resources.",
        RENAME: "Project renamed",
        RENAME_ERROR: "Error renaming editor",
        LOADING: "Loading projects",
        TITLE: "Projection Engine",
        LABEL_PROJECTS: "Projects",
        PROJECTS: "Your projects",
        CREATE: "Create editor",
        EMPTY: "Nothing found",
        SEARCH: "Search",
        SET_AS_DEFAULT: "Default",
        PROJECT_CREATED: "Project created",
        DONE: "Done",
        IS_DEFAULT_VERSION: "Default version",
        NO_RELEASES: "No releases found",
        INSTALL: "Install",
        DOWNLOADS: "Downloads",
        NEW_NAME: "New name",
        DELETE: "Delete",
        SHOW_IN_EXPLORER: "Show in explorer",
        NEVER: "Never",
        PROJECT: "Project",
        TOGGLE_DOWNLOADS: "Toggle downloads",
        LAST_MODIFIED: "Last modified",
        CREATION: "Creation date",
        RECENT: "Recent",
        DOUBLE_CLICK: "Double click to rename.",
        FAVORITE: "Toggle favorite.",
        DOWNLOAD_FINISHED: "Download finished.",
        NOT_COMPATIBLE: "This version is not compatible with your OS.",
        UNINSTALL: "Uninstall",
        CHANGE_BASE_DIR: "Change source directory",
        NO_VERSION: "No version linked.",
        NO_UPDATES: "You are up-to-date.",
        CHECK_UPDATE_HUB: "Check for updates",
        FETCHING_UPDATES: "Fetching updates.",
        ERROR_UPDATE: "Some error occurred during update.",
        INSTALLING_UPDATES: "Installing updates, your app may restart after some time."
    }
    static  VERSION = "1.0.0-beta"

}